/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IAirDropHandler } from "./IAirDropHandler";
export type { IStakingHandler } from "./IStakingHandler";
