/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as interfaces from "./interfaces";
export * as mocks from "./mocks";
export { CaminoHub__factory } from "./CaminoHub__factory";
export { SimpleAirdropHandler__factory } from "./SimpleAirdropHandler__factory";
export { SimpleStakingHandler__factory } from "./SimpleStakingHandler__factory";
